### ISSUE TITLE
Trying to add a class ".glow" to my colors when clicked

### ISSUE THREAD

**Issue by tayb18** [tayb18/R2D2#1]
Hey @phlco ,

I have been trying to figure out how to add/toggle my glow class to different squares when clicked for about an hour. Tried lots of options, and feel like I'm close I just can't get it quite right. Any help is welcome and appreciated :) 

https://github.com/tayb18/R2D2/blob/master/main.js
(lines 32 - 43)

**Comment by phlco** [comment]
You've got some confusion in your `addGlow` function regarding events and "this"

Remember when you're adding event listeners the callback function will be passed the event object.

"this" changes and refers to the calling object, which with your event listeners is the window. You don't want to attach the class "glow" to the window, but the DOM node you're clicking on. How do you have access to the DOM node you're clicking on?  

Look at the code below.

``` js
        // you need to pass the event object as a parameter
    var addGlow = function (event){
        if (event.target.id === '#white'){
                      //  " this " is a contextual keyword that refers to the calling object
                      // your  function is run in the global scope so "this" is the window.
              this.classList.toggle('glow');  // is there anything else in your code above that references that actual DOM node you want to toggle the class of glow on?
                 //
    };
```

**Comment by tayb18** [comment]
I think that I am following the logical path you're leading me down, so I have replaced my 'this's with the name of the variables I would like to attach glow class to (white, blue, grey, black). Still no love. This was actually the first thing I tried, before giving the 'this' method a try. Is there anything else I'm missing?

``` javascript
        if (event.target.id === '#white'){
            white.classList.toggle('glow');
            }
```

**Comment by tayb18** [comment]
Problem solved. I didn't need the # in my event.target.id === '#white'. Dumb.
Also, just discovered that this:
        event.target.classList.toggle('glow');
is the same thing as ALLL OF MY IF ELSES! Magic. 
Thank you!
