### ISSUE TITLE
Hidden P is taking up space on my webpage

### ISSUE THREAD

**Issue by tayb18** [tayb18/R2D2#2]
https://github.com/tayb18/R2D2 

``` javascript
<div class="content">
        <p class="instructions">R2D2 needs your help delivering the plans for the Death Star safely to the Rebel Base. There's just one problem. YOU DON'T SPEAK DROID! R2 will help you make sense of his beeps and flashes. Copy the pattern of colors and beeps R2 says by clicking the colors in the correct order to learn his language. Master the language of droids and help R2 save the Galaxy from the WRATH OF THE DEATH STAR!</p>
        <p class="loseAlert hidden">Oh no! You must have whistled instead of beeped. Your Droid language learning is coming along, but it wasnt enough to save the Galaxy from the wrath of the death star. Press start to try again!</p>
        <button class="start">START</button>
</div>
```

Hello @phlco ,

Hope you're having a nice weekend and not responding to too many issues.. 

Quick question for you. I recently added a new <p> in my html doc with the class hidden. In my JS I am working on making it so that when a player loses, the <p class="instructions"> adds class hidden and <p class="loseAlert" removes class hidden. The problem is, the hidden class is still taking up space in the document and moving my start button too far down the page. 

I recall hearing one of the instructors mention this at some point in class, but I have no notes on it and google isn't telling me what I want to hear. Any suggestions??

Thank you, see ya soon! 

-Taylor

**Comment by tayb18** [comment]
Hello @phlco ,

Hope you're having a nice weekend and not responding to too many issues..

Quick question for you. I recently added a new P tag in my html doc with the class hidden. In my JS I am working on making it so that when a player loses, the 'P class instructions' adds class hidden and 'P class loseAlert' removes class hidden. The problem is, the hidden class is still taking up space in the document and moving my start button too far down the page.

I recall hearing one of the instructors mention this at some point in class, but I have no notes on it and google isn't telling me what I want to hear. Any suggestions??

Thank you, see ya soon!

-Taylor

**Comment by sungchoi** [comment]
@tayb18 

Hi Taylor,

We did mention the difference between `visibility: hidden;` and `display: none;`. The first one still takes up space on the document. The latter doesn't.

Please close this issue if that solves your problem, otherwise add a comment with more info.

**Comment by tayb18** [comment]
That was so simple and so helpful. Thank you for the quick response, I really appreciate it!
