### ISSUE TITLE
README

### ISSUE THREAD

**Issue by tayb18** [tayb18/R2D2#4]
Hello @sungchoi ,

I'm making my readme file and I see in the instructions that it should contain our pseudocoding and user stories. I took images of my notes for each of these and saved them in an appropriately named variable in the repository. Does that still count? Or should I figure out how to include the images in the readme file itself??

**Comment by sunsheeppoplar** [comment]
Regarding the images, you could always save them to an appropriately named folder (github images, assets, something like that) and then push that to repo, from where you could just use relative linking on your README to make it look nice.

**Comment by tayb18** [comment]
Is there a cheat sheet to styling the readme?? I realized that #this makes words a heading. But my styling skills stop there... :)

**Comment by tayb18** [comment]
@sunsheeppoplar

**Comment by annarankin** [comment]
@tayb18 Check out [this markdown guide](http://assemble.io/docs/Cheatsheet-Markdown.html).
![unicorn](https://cdn2.scratch.mit.edu/get_image/gallery/276726_200x130.png)

**Comment by tayb18** [comment]
the best @annarankin
